### ISSUE TITLE
Surviving Severe Weather Graphic

### ISSUE THREAD

**Issue by jphearse** [seanrlindsay/ist5313-final-project-weather#13]
Navigation jumps down on test.
When going to the "test" site; there is an "s" on the far left side. 
Introduction navigation jumps up.
Sub-navigation bar is dark.  Maybe a lighter color to show the topics better.
Tornadoes is spelled with an "s", on the page, but the navigation link it is spelled with no "s".
Very creative with the navigation links opening up on the top bar.  
Looking good!  Looks like a great topic and very exciting to see what will be the content!  Good Job!

**Comment by upcag** [comment]
Joe check w/Sean about this comment because they said they like the way navigation was set up - its different.
