### ISSUE TITLE
Drought, Preparedness, Test Pages

### ISSUE THREAD

**Issue by seanrlindsay** [seanrlindsay/ist5313-final-project-weather#16]
At the bottom of the page, you are missing dividers between your buttons for drought, preparedness, test pages. That will be fixed with CSS later i'm sure! :) All of the links work properly

**Comment by upcag** [comment]
Joe let me know when this is done, so that I can close out this comment

**Comment by jphearse** [comment]
The "|" were left out on purpose, I believe. The gating that we have to have would leave the "|" visible when the links were not visible. Ask Sean if we should add them anyways, for the time being.
