### ISSUE TITLE
test page

### ISSUE THREAD

**Issue by upcag** [seanrlindsay/ist5313-final-project-weather#17]
there is a random "s" in your content.  Was inconsistent with other content areas.  Was this on purpose?

**Comment by upcag** [comment]
Are you getting rid of the "s" or does Sean get rid of it?

**Comment by jphearse** [comment]
I think I got rid of the S. Double check though. I have an issue with the Final test html connecting to github that might be conflicting.

**Comment by upcag** [comment]
fixed
