### ISSUE TITLE
storyboard

### ISSUE THREAD

**Issue by jphearse** [seanrlindsay/ist5313-final-project-weather#21]
Reviewing in Firefox  - On Hurricanes - Media Page/Interactive/Mini Quiz - sub navigation has a line to separate Mini Quiz with space. All other pages do not have this | after Mini Quiz.

**Comment by jphearse** [comment]
Reviewing in Firefox  - The | between Thunderstorms and Drought is missing until you select Thunderstorms then goes away once you select Preparedness. This happens again between Drought and Preparedness when you click on Test.

**Comment by upcag** [comment]
The | is not displaying - let me know when you correct

**Comment by jphearse** [comment]
I added the |
